name: npm

on:
  push:
    branches: ["next"]
  pull_request:
    branches: ["next"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Benchmark Run
        run: |
          npm install -g artillery
          artillery run benchmark.yml
