name: npm

on:
  push:
    branches: ["next"]
  pull_request:
    branches: ["next"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_API_KEY = ${{ secrets.HOST_IP }}" | sudo tee -a .env
          echo "NEXT_PUBLIC_API_HOST = ${{ secrets.HOST_IP }}" | sudo tee -a .env
          cat .env
          ls -lath

      - name: Install yarn
        run: |
          npm install -g yarn
          yarn add next
          yarn install
          sudo ls /app/node_modules/.bin
          sudo cp .env /app

      - name: Yarn build
        run: cd app && yarn build

      - name: Compress project file
        run: tar -czvf ./project.tar.gz ./app

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github
          key: ${{ secrets.ID_RSA_PRIVATE }}
          known_hosts: ${{ secrets.HOST_IP }}

      - name: SSH Keyscan
        run: |
          ssh-keyscan -p 22 -H ${{ secrets.HOST_IP }}  >> ~/.ssh/known_hosts

      - name: Copy file
        run: |
          scp -i ~/.ssh/github ./bash.sh ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}:/home/${{ secrets.HOST_USERNAME }}/artifact
          scp -i ~/.ssh/github ./deploy.yml ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}:/home/${{ secrets.HOST_USERNAME }}/artifact
          scp -i ~/.ssh/github ./project.tar.gz ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}:/home/${{ secrets.HOST_USERNAME }}/artifact

      - name: Run Ansible
        run: |
          ssh -i ~/.ssh/github  ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }} 'bash -s < /artifcat/bash.sh'
